version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    command: redis-server --requirepass password

  minio:
    image: minio/minio:latest
    ports: ["9000:9000", "9001:9001"]
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  auth-service:
    build: ../auth-service
    env_file:
      - ../auth-service/.env
    ports: ["3001:3001"]

  course-service:
    build: ../course-service
    env_file:
      - ../course-service/.env
    ports: ["3002:3002"]

  payment-service:
    build: ../payment-service
    env_file:
      - ../payment-service/.env
    ports: ["3003:3003"]

  nginx:
    image: nginx:alpine
    ports: ["8080:80"]
    volumes:
      - ./docker-compose:/etc/nginx/conf.d:ro
    depends_on:
      - auth-service
      - course-service
      - payment-service

volumes:
  mongodb_data:
  minio_data:
